on: pull_request
name: Terraform
jobs:
  filter-to-pr-open-synced:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: filter-to-pr-open-synced
      uses: actions/bin/filter@master
      with:
        args: action 'opened|synchronize'
    - name: terraform-fmt
      uses: hashicorp/terraform-github-actions/fmt@v0.3.6
    - name: terraform-init
      uses: hashicorp/terraform-github-actions/init@v0.3.6
      env:
        TF_ACTION_WORKING_DIR: "./src"
    - name: terraform-validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.6
      env:
        TF_ACTION_WORKING_DIR: "./src"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: terraform-plan
      uses: hashicorp/terraform-github-actions/plan@v0.3.6
      env:
        TF_ACTION_WORKING_DIR: "./src"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKSPACE: default
